
import { Topic } from './types';

export const TOPICS: Topic[] = [
  { id: 'osi-model', title: 'Einführung in das OSI-Modell', category: 'Grundlagen', description: 'Die 7 Schichten der Netzwerkkommunikation.' },
  { id: 'agile', title: 'Agile Arbeitsmethoden', category: 'Management', description: 'Scrum, Kanban und agile Prinzipien in der IT.' },
  { id: 'net-sizes', title: 'Netzwerkgrößen', category: 'Grundlagen', description: 'LAN, MAN, WAN, PAN und GAN.' },
  { id: 'net-components', title: 'Netzwerkkomponenten', category: 'Hardware', description: 'Hubs, Switches, Router und Bridges.' },
  { id: 'phys-infra', title: 'Physikalische Infrastruktur', category: 'Hardware', description: 'Kabeltypen, Glasfaser und Patchpanels.' },
  { id: 'topologies', title: 'Topologien', category: 'Design', description: 'Stern, Bus, Ring und Mesh-Strukturen.' },
  { id: 'ipv4-p1', title: 'IPv4 Adressen Teil 1', category: 'Protokolle', description: 'Grundlagen der binären Adressierung.' },
  { id: 'ipv4-p2', title: 'IPv4 Adressen Teil 2', category: 'Protokolle', description: 'Adressklassen und private Bereiche.' },
  { id: 'subnetting', title: 'Subnetting & CIDR', category: 'Protokolle', description: 'Netzwerke effizient unterteilen.' },
  { id: 'static-dynamic', title: 'Statische/Dynamische IPs', category: 'Konfiguration', description: 'Verwaltung von IP-Adressbereichen.' },
  { id: 'packet-tracer', title: 'Cisco Packet Tracer', category: 'Simulation', description: 'Netzwerksimulation in der Praxis.' },
  { id: 'dhcp', title: 'Einführung in DHCP', category: 'Dienste', description: 'Automatische IP-Zuweisung.' },
  { id: 'vlan-p1', title: 'VLANs Teil 1', category: 'Switching', description: 'Virtuelle LANs und Segmentierung.' },
  { id: 'vlan-p2', title: 'VLANs Teil 2', category: 'Switching', description: 'Trunking und Inter-VLAN Routing.' },
  { id: 'routing-p1', title: 'Routing & Gateways 1', category: 'Routing', description: 'Grundlagen der Paketweiterleitung.' },
  { id: 'routing-p2', title: 'Routing & Gateways 2', category: 'Routing', description: 'Dynamische Routing-Protokolle.' },
  { id: 'acl', title: 'Einführung ACL', category: 'Sicherheit', description: 'Zugriffskontrolllisten konfigurieren.' },
  { id: 'troubleshoot-route', title: 'Troubleshooting Routing', category: 'Fehlersuche', description: 'Routing-Probleme systematisch lösen.' },
  { id: 'ipv6-p1', title: 'IPv6 Teil 1', category: 'Protokolle', description: 'Die Zukunft der Adressierung.' },
  { id: 'ipv6-p2', title: 'IPv6 Teil 2', category: 'Protokolle', description: 'Header und Adresstypen.' },
  { id: 'practice-config', title: 'Praxisübung Netzwerkkonfiguration', category: 'Praxis', description: 'Komplette Szenarien aufbauen.' },
  { id: 'file-win', title: 'Dateifreigabe Windows', category: 'Betriebssysteme', description: 'SMB und NTFS Berechtigungen.' },
  { id: 'file-linux', title: 'Dateifreigabe Linux', category: 'Betriebssysteme', description: 'Samba und NFS unter Linux.' },
  { id: 'file-practice', title: 'Dateifreigabe Praxis', category: 'Praxis', description: 'Cross-Plattform Sharing.' },
  { id: 'print-scan', title: 'Drucker & Scanner', category: 'Peripherie', description: 'Ressourcen im Netz teilen.' },
  { id: 'osi-troubleshoot', title: 'Troubleshooting OSI', category: 'Fehlersuche', description: 'Layer-basierte Fehlersuche.' },
  { id: 'dns-intro', title: 'Einführung in DNS', category: 'Dienste', description: 'Namensauflösung im Internet.' },
  { id: 'dns-practice', title: 'DNS in der Praxis', category: 'Dienste', description: 'Zonendateien und Root-Server.' },
  { id: 'active-directory', title: 'Active Directory (AD)', category: 'Dienste', description: 'Zentrale Benutzerverwaltung.' },
  { id: 'monitoring', title: 'Netzwerk-Monitoring', category: 'Management', description: 'Wireshark und SNMP.' },
  { id: 'net-services', title: 'Netzwerkdienste', category: 'Dienste', description: 'HTTP, FTP, SMTP und mehr.' },
  { id: 'firewall', title: 'Einführung Firewall', category: 'Sicherheit', description: 'Paketfilter und Stateful Inspection.' },
  { id: 'dmz', title: 'Einführung DMZ', category: 'Sicherheit', description: 'Demilitarisierte Zonen für Server.' },
  { id: 'proxy-squid', title: 'Proxy / Squid', category: 'Sicherheit', description: 'Caching und Web-Filterung.' },
  { id: 'vpn', title: 'VPN Grundlagen', category: 'Sicherheit', description: 'Sichere Remote-Verbindungen.' }
];
